### ISSUE TITLE
Add logout functionality to the app

### ISSUE THREAD

**Issue by root458** [droidconKE/flutterconKEApp#87]
I am unable to log out of the application. This issue is when I wish to sign in with a different account.

**Comment by MillerAdulu** [comment]
This can probably be approached by having a modal pop up when you tap the profile icon on the app bar then have a user log out.

**Comment by root458** [comment]
Agreed. However, I think the profile can be a great place for users to update their details such as the Twitter handles, Bio, specialties etc. as observed from the speakers' profiles. The modal pop up can the placed somewhere on this screen. This is my proposal since I haven't spotted a screen dedicated to this.

**Comment by MillerAdulu** [comment]
@root458,

This isn't desired functionality for the app at the moment. Event-goers should only be able to log in, bookmark events and leave feedback. The social media handles for speakers are added directly on the backend so that the app is mostly informational to allow attendees navigate the conference comfortably. 

So the currently missing thing here would be to just have a quick logout pop up which should be light work.

**Comment by root458** [comment]
@MillerAdulu 

Git it. This is well in order.

**Comment by MillerAdulu** [comment]
Do let me know if you would like to take this up, then I can assign it to you.

**Comment by root458** [comment]
@MillerAdulu,

I can take this up.

**Comment by MillerAdulu** [comment]
Assigned. Small enough to come with that dark theme PR. Do ensure to keep changes concise.

**Comment by root458** [comment]
OK @MillerAdulu
